### ISSUE TITLE
not train the proper model for detecting car similar objects.

### ISSUE THREAD

**Issue by lonl** [Xiangyu-CAS/R2CNN.pytorch#3]
Hi,
When I train the text dataset, it could give good predictions with trained weights. 

However, when I train a new dataset for predicting cars and ships. However, when I conduct the inference process, there is  nothing predicted in images. Could you help give some suggestions?

**Comment by Xiangyu-CAS** [comment]
Hi，thank you for attention. I am not sure what your problem exactly is but I suggest you to check annotations first. For rotate detection, the annotation should be arranged in anti-clock-wise order and begin from left-top point.

Is your dataset working in vanilla faster RCNN (such as like detectron2, maskrcnn-benchmark) ? if it works, the error seems to be the four points annotation. (x1, x2, y1, y2)

**Comment by lonl** [comment]
Thank you very much, I will re-check it.
